spring:
  profiles:
    active: "dev"

---
spring:
  security:
    user:
      name: admin
      password: fuckingashole551
  profiles: "dev"
  boot:
    admin:
      client:
        url: "https://articleflow.herokuapp.com/"
        username: admin
        password: fuckingashole551
        instance:
          metadata:
            user:
              name: admin
              password: fuckingashole551
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8080
