spring:
  profiles:
    active: "dev"

---
spring:
  profiles: "dev"
  boot:
    admin:
      client:
        url: "http://localhost:8080"
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8080
